= Qute - Detail
Hartl Anna
1.0.1, 2021-26-12:
ifndef::imagesdir[:imagesdir: images]
:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]


include::https://quarkus.io/guides/qute[Tutorial]

== Was macht's?
QUarkus TEmplates - Templating Engine.
Reflexion ist minimiert.

Reflexion - zur Laufzeit den Aufbau von Objecten zu erkennen und darauf zu zugreifen

Rendern - zur Darstellung Vorbereiten in unserem Fall ein html Dokument

== Andere Technologien
Angular

== Schritte zum Erfolg

1. Hello Resource erstellt

[,shell]
----
curl -w "\n" http://localhost:8080/hello?name=Anna
----

Ergebnis: Hello Anna!

2. Alle templates werden in Unterordner angelegt, damit ist es übersichlicher

    /src/main/resources/templates

3. Item Klasse hinzugefügt


.Test
[NOTE]
http://localhost:8080/item/1

4. Extension Template hinzugefügt
Berechnet einen vergünstigten Preis


.Test
[NOTE]
http://localhost:8080/item/1

Anders als oben gibt es nun ein zusätzliches Feld Discounted Preis
