= Validierung
Hartl Anna
1.0.2, 2021-26-12:
ifndef::imagesdir[:imagesdir: images]
:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]


include::https://2122-4ahif-nvs.github.io/01-microproject-AnnaHartl/validierung-detail.html[Detail Dokumentation]

== Dependency
----
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-hibernate-validator</artifactId>
</dependency>
----

== Validierung der Klasse Employee

----
@NotBlank() //<1>
public String firstName;

@NotBlank(message = "Lastname should not be blank")//<2>
public String lastName;

@Min(value = 500)
    public double salary;
----

<1> Ohne parameter Message
<2> Mit eingens definierter Nachricht

NOTE: Wenn keine Message angegeben wird, wird die default Nachricht in Betriebssystemsprachen ausgegeben

== Möglichkeiten der Validierung
=== Endpoint Validierung

----
@POST
    @Path("/add")
    @Transactional
    public void AddEmp(@Valid Employee newEmp) {
        repo.persist(newEmp);
    }
----

Bei verletzung einer order mehrer Regeln wird folgende Meldung im body zurück gegeben

----
{
  "classViolations": [],
  "parameterViolations": [
    {
      "constraintType": "PARAMETER",
      "message": "muss größer-gleich 500 sein",
      "path": "AddEmp.newEmp.salary",
      "value": "100.0"
    },
    {
      "constraintType": "PARAMETER",
      "message": "darf nicht leer sein",
      "path": "AddEmp.newEmp.firstName",
      "value": ""
    },
    {
      "constraintType": "PARAMETER",
      "message": "Lastname should not be blank",
      "path": "AddEmp.newEmp.lastName",
      "value": ""
    }
  ],
  "propertyViolations": [],
  "returnValueViolations": []
}
----

=== Repository Validierung
Hier wird nicht im Endpoint sondern gleich zentral im Repository Validiert

----
public void addEmp(@Valid Employee newEmp) {
    this.persist(newEmp);
}
----

== Testen
Zum testen wird die ConstraintViolationException abgefangen die geworfen wird bei einer verletzung.


== Eigene Validierung

=== Interface Constraint
Damit wir eine eigene Annotation benutzen können

=== Klasse Validator
Diese führt die Validierung durch, eine Methode wird implementiert isValid.

----
@Override
public boolean isValid(String text,ConstraintValidatorContext cxt) {

    return text != null && !text.contains("superbad") && !text.contains("bad"); //<1>
}
----

<1> Es wird darauf überprüft, dass das Wort nicht "bad" und "superbad" enthält

In der Product Klasse angewendet
----
@NoBadWordsConstraint
    public String description;
----

