= Validierung - Detail
Hartl Anna - erstellt am 26.12.2021
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]


include::https://quarkus.io/guides/validation[Tutorial]


== Was machts?
Felder einschränken auf eine definierte Regel z. B. Titel feld darf nicht leer sein.
Valisierung direkt bei Entitäten nicht auf der Webseite, damit auch wenn die Webseite umgangen wird z. B. mit Tests die Werte gültig sind.

== Schritte zum Erfolg
1. Annotationen hinzugefügt
2. Methoden im Resource hinzugefügt
3. Index.html geändert zu einem Formular

== Erklärung einzelner Annotationen

@Min(Message, value) = Der Wert den eine Zahl midestens haben muss

@Max(Message, value) = Der Wert den eine Zahl maximal haben darf

@NotBlank(message="Invalid") = Prüft auf Leerzeichen der ganze String darf nicht nur aus diesen bestehen

@Size(min = 4, max = 15, message = "username should have size [{min},{max}]") = Länge muss zwischen den Werten liegen

@NotNull(message = "username may not be blank")
= keine Null Werte

@Pattern(regexp = "[a-zA-Z]")
= muss ein bestimmte Folge von Zeichen enthalten

NOTE: Diese Annotationen können auch direct bei einem Methoden Parameter stehen


== Eigene Validierung

=== Interface Constraint
Damit wir eine eigene Annotation benutzen können

=== Klasse Validator
Diese führt die Validierung durch, eine Methode wird implementiert isValid.

----
@Override
public boolean isValid(String text,ConstraintValidatorContext cxt) {

    return text != null && !text.contains("superbad") && !text.contains("bad"); //<1>
}
----

<1> Es wird darauf überprüft, dass das Wort nicht "bad" und "superbad" enthält

In der Entität verwendet
----
@NoBadWordsConstraint
    public String description;
----


