GET http://localhost:8080/employee/getAll

###
POST http://localhost:8080/employee/add
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "salary": 100
}

###
POST http://localhost:8080/employee/add
Content-Type: application/json

{
  "firstName": "Hansi",
  "lastName": "Hern",
  "salary": 500
}
